# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{apple_push_notification}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Soffes", "Fabien Penso"]
  s.date = %q{2009-11-10}
  s.description = %q{Rails plugin for Apple Push Notifications}
  s.email = %q{sam@samsoff.es}
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "Rakefile",
     "Readme.markdown",
     "VERSION",
     "init.rb",
     "install.rb",
     "lib/app/models/apple_push_notification.rb",
     "lib/apple_push_notification.rb",
     "lib/db/migrate/20090406132059_create_apple_push_notifications.rb",
     "tasks/apple_push_notification_tasks.rake",
     "test/apple_push_notification_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/samsoffes/apple_push_notification}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Rails plugin for Apple Push Notifications}
  s.test_files = [
    "test/apple_push_notification_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

